todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]

todoapp/urls.py
from django.urls import path
from .views import *

app_name = 'todoapp'

urlpatterns = [
    path('', index, name='index'),
    path('update/<pk>', TaskUpdateView.as_view(), name='update'),
    path('delete/<pk>', TaskDeleteView.as_view(), name='delete'),
    
]

todoapp/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=120)
    due_date = models.DateField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    completed = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.title
    

todoapp/forms.py
from django import forms

class TaskForm(forms.Form):
    title = forms.CharField(max_length=120, widget=forms.TextInput())
    due_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'class': 'datepicker'}))
    completed = forms.BooleanField(required=False)
    description = forms.CharField( required=False, widget=forms.Textarea(attrs={'class': 'materialize-textarea'}))

todoapp/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView,DeleteView

from .models import Task
from .forms import TaskForm


# used function based view to pass multiple context
# TODO: add due_date and completed indicator

def index(request):
    tasklist = Task.objects.all()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        print(request.POST)
        if form.is_valid():
            print("Valid")
            Task.objects.create(**form.cleaned_data)
        else:
            print("invalid")

    form = TaskForm()

    context = {
        'tasklist': tasklist,
        'form': form
    }
    return render(request, 'todoapp/index.html', context)


class TaskDetailView(DetailView):
    model = Task
    context_object_name = 'task'
    template_name = "todoapp/detail.html"


# TODO: add Materialize CSS to elements, this uses modelform by default
# TODO: adding due date later doesn't work

class TaskUpdateView(UpdateView):
    model = Task
    fields = '__all__'
    template_name = "todoapp/update.html"

    # reverse doesn't work with class based views, equivalent is reverse_lazy
    success_url = reverse_lazy('todoapp:index')


class TaskDeleteView(DeleteView):
    model = Task
    context_object_name = 'blog_delete'
    template_name = "todoapp/delete.html"
    
    success_url = reverse_lazy('todoapp:index')

todoapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
    

    <title>Todo - {% block title %}{% endblock title %}</title>

    {% block head %}{% endblock head %}

</head>
<body>

    <!-- Persistant Navigation Bar -->
    <nav>
        <div class="nav-wrapper blue">
            <a href="{% url 'todoapp:index' %}" class="brand-logo center">Django To-Do App</a>
        </div>
    </nav>

    {% block above_content %}
    {% endblock above_content %}
    
    <!-- Materialize CSS container -->
    <div class="content">
        {% block content %}{% endblock content %}
    </div> <!-- Container End -->

    {% block below_content %}
    {% endblock below_content %}

    <!-- Initialize all Materialize CSS JS components with default values -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.collapsible');
        var instances = M.Collapsible.init(elems, {});
  });
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.datepicker');
        var instances = M.Datepicker.init(elems, {'format': 'yyyy-mm-dd'});
  });

</script>

</body>
</html>

todoapp/templates/todoapp/delete.html
{% extends 'base.html' %}

{% block title %}Delete {{ blog_delete }}{% endblock title %}

{% block above_content %}
<div style="height: 5em;"></div>
{% endblock above_content %}

{% block content %}

<form method="POST" autocomplete="off">
    {% csrf_token %}

    <div class="center">
        <h4 class="flow-text">Delete "{{ blog_delete }}"?</h4>
        <input type="submit" value="Yes" class="btn red">
        <a href="{% url 'todoapp:index' %}" class="btn green">No</a>
    </div>

    

</form>
{% endblock content %}

todoapp/templates/todoapp/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block above_content %}
<div style="height: 5em;"></div>
{% endblock above_content %}

{% block content %}


<form method='POST' autocomplete="off">
    {% csrf_token %}
    <div class="row">
        <div class="input-field col l6 offset-l2 m7 offset-m1 s12">
            {{ form.title }}
            <label for="id_title">Task</label>
        </div>
        <div class="input-field col l2 m3 s12">
            {{ form.due_date }}
            <label for="id_due_date">Due Date</label>
        </div>
    </div>
    <div class="row">
        <div class="input-field col l8 offset-l2 m10 offset-m1 s12">
            {{ form.description }}
            <label for="id_description">Description</label>
        </div>
    </div>
    <div class="input-field center">
        <button type="submit" class="btn blue waves-effect">Add<i class="material-icons right">add</i></button>
    </div>

</form>



{% if tasklist %}
<div class="row">
    <div class="col l8 offset-l2 m10 offset-m1 s12">
        <ul class="collapsible popout">
            {% for task in tasklist %}
            <li>
                <div class="collapsible-header">
                    <p>
                        {% if task.completed == True %}
                        <strike>{{ task.title }}</strike>
                        {% else %}
                        {{ task.title }}
                        {% endif %}
                    </p>
                    {% if task.due_date %}
                    <span class="new badge red" data-badge-caption="{{ task.due_date }}"></span>
                    {% else %}
                    <span class="new badge green" data-badge-caption="Self Paced"></span>
                    {% endif %}
                </div>
                <div class="collapsible-body">
                    {% if task.description %}
                    <span>{{ task.description }}</span>
                    {% else %}
                    <span class='grey-text'>NO DESCRIPTION</span>
                    {% endif %}
                    <br>
                    <a href="{% url 'todoapp:update' task.id %}" class="btn green">Update</a>
                    <a href="{% url 'todoapp:delete' task.id %}" class="btn red">Delete</a>
                </div>

            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% else %}
<h5 class="center-align">No Tasks Available!</h5>
{% endif %}

{% endblock content %}

{% block below_content %}



{% endblock below_content %}

todoapp/templates/todoapp/update.html
{% extends 'base.html' %}


{% block title %}Update{% endblock title %}

{% block above_content %}
<div style="height: 5em;"></div>
{% endblock above_content %}

{% block content %}




<form method="POST" autocomplete="off">
    {% csrf_token %}
    <div class="row">
        <div class="input-field col l6 offset-l2 m7 offset-m1 s12">
            {{ form.title }}
            <label for="id_title">Task</label>
        </div>
        <div class="input-field col l2 m3 s12">
            {{ form.due_date }}
            <label for="id_due_date">Due Date</label>
        </div>
    </div>
    <div class="row">
        <div class="input-field col l8 offset-l2 m10 offset-m1 s12">
            {{ form.description }}
            <label for="id_description">Description</label>
        </div>
    </div>
    <div class="row">
        <div class="input-field col l8 offset-l2 m8 offset-m1">
            <label>
                {{ form.completed }}
                <span>Completed</span>
            </label>
        </div>
    </div>
    <div class="row">
        <div class="input-field center">
            <input type="submit" value="Update" class="btn blue lighten-1">
        </div>
    </div>
</form>



{% endblock content %}

{% block below_content %}
<script>
    var description = document.getElementById('id_description');
    description.className = "materialize-textarea";

    var due_date = document.getElementById('id_due_date');
    due_date.className = "datepicker"
</script>
{% endblock below_content %}